server:
  port: 8002

spring:
  application:
    name: service-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.128:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.10.128:8080
