server:
  port: 80

spring:
  application:
    name: service-consumer
#  profiles:
#    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.128:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.10.128:8080
      eager: false
      datasource:
        dsl:
          nacos:
            server-addr: 192.168.10.128:8848
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data_type: json
            rule_type: flow

# 开启sentinel对openfeign的支持
feign:
  sentinel:
    enabled: true
